// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrationItemsApp.Data;

namespace RegistrationItemsApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220103204452_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RegistrationItemsApp.Models.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Form1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Form2"
                        });
                });

            modelBuilder.Entity("RegistrationItemsApp.Models.RegistrationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SelectedValueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("RegistrationItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Reikia atlikti rangos darbus",
                            SelectedValueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rangos darbus atliks",
                            SelectedValueId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Verslo klientas",
                            SelectedValueId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Skaičiavimo metodas",
                            SelectedValueId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Svarbus klientas",
                            SelectedValueId = 1
                        });
                });

            modelBuilder.Entity("RegistrationItemsApp.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegistrationItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationItemId");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = " "
                        },
                        new
                        {
                            Id = 2,
                            Name = " "
                        },
                        new
                        {
                            Id = 3,
                            Name = " "
                        },
                        new
                        {
                            Id = 4,
                            Name = " "
                        },
                        new
                        {
                            Id = 5,
                            Name = " "
                        },
                        new
                        {
                            Id = 6,
                            Name = "Taip"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ne"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Metinis rangovas"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mėnesinis rangovas"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Taip"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ne"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Automatinis"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Rankinis"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Taip"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ne"
                        });
                });

            modelBuilder.Entity("RegistrationItemsApp.Models.RegistrationItem", b =>
                {
                    b.HasOne("RegistrationItemsApp.Models.Form", "Form")
                        .WithMany("RegistrationItems")
                        .HasForeignKey("FormId");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("RegistrationItemsApp.Models.Value", b =>
                {
                    b.HasOne("RegistrationItemsApp.Models.RegistrationItem", "RegistrationItem")
                        .WithMany("Values")
                        .HasForeignKey("RegistrationItemId");

                    b.Navigation("RegistrationItem");
                });

            modelBuilder.Entity("RegistrationItemsApp.Models.Form", b =>
                {
                    b.Navigation("RegistrationItems");
                });

            modelBuilder.Entity("RegistrationItemsApp.Models.RegistrationItem", b =>
                {
                    b.Navigation("Values");
                });
#pragma warning restore 612, 618
        }
    }
}
